[package]
name = "tinkoff_investments"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.1"
serde = "1.0.126"
serde_json = "1.0.64"
hyper = {version="0.14.9", features=["full"]}