name: Rust

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      run: cargo login ${{ secrets.CARGO }}
    - name: Publish
      run: cargo publish
