name: Rust

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test
      env:
        TINKOFF_SANDBOX_TOKEN: ${{ secrets.TINKOFF_SANDBOX_TOKEN }}

